### ISSUE TITLE
F12対策したい

### ISSUE THREAD

**Issue by kentama7** [bancha-project/bancha-memo#4]

**Comment by kentama7** [comment]
win.webContents.on("devtools-opened", () => { win.webContents.closeDevTools(); });

**Comment by ahyaemon** [comment]
The solution:

mainWindow = new BrowserWindow({
width: 800,
height: 600,
webPreferences: {
devTools: false
}
})

https://discuss.atom.io/t/a-way-to-prevent-developer-tools/29746/8

**Comment by ahyaemon** [comment]
04f05a6d3e0b3865e9f96da53ecd5f4e0a25e1f4
